#cloud-config
package_update: true
package_upgrade: true
packages:
  - docker.io
  - openjdk-17-jre
  - apache2
  - curl
  - gnupg
 
runcmd:
  # Démarrer et activer docker    .
  - sudo apt update -y
  - sudo apt install apache2 -y
  - echo "Love from paul" > /var/www/html/index.html
  - sudo apt install docker.io -y
  - systemctl enable docker
  - systemctl start docker

  - sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
  - docker-compose --version
  - sudo apt update
  - sudo apt install docker-compose-plugin -y
  - docker-compose build
  - sudo apt-get remove docker docker-engine docker.io containerd runc
  - sudo apt-get update
  - sudo apt-get install ca-certificates curl gnupg lsb-release
  - sudo mkdir -p /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  - sudo apt-get update
  - sudo apt-get install docker-compose-plugin -y
  - docker compose version
   

  # Ajouter la clé Jenkins et repo
  - sudo apt update
  - sudo apt install fontconfig openjdk-21-jre -y
  - sudo wget -O /etc/apt/keyrings/jenkins-keyring.asc https://pkg.jenkins.io/debian/jenkins.io-2023.key
  - echo "deb [signed-by=/etc/apt/keyrings/jenkins-keyring.asc]" https://pkg.jenkins.io/debian binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null
  - sudo apt-get update -y
  - sudo apt-get install jenkins -y

  # Ajouter Jenkins au groupe docker et démarrer Jenkins
  - usermod -aG docker jenkins
  - systemctl enable jenkins
  - systemctl start jenkins
  - systemctl restart jenkins

  # Attendre que Jenkins démarre et récupérer le mot de passe admin
  - bash -c "until curl -s http://localhost:8080 > /dev/null; do sleep 10; done"
  - PASSWORD=$(cat /var/lib/jenkins/secrets/initialAdminPassword)
  
  # Modifier la page par défaut d’Apache pour afficher le mot de passe Jenkins
  - echo "Jenkins initial admin password</h1><p>${PASSWORD}" > /var/www/html/index.html

  # Redémarrer Apache
  - systemctl restart apache2