#cloud-config
package_update: true
package_upgrade: true
packages:
  - docker.io
  - openjdk-17-jdk  # Utiliser JDK au lieu de JRE
  - apache2
  - curl
  - gnupg
  - docker-compose-plugin  # Installer via APT pour éviter les conflits

runcmd:
  # Démarrer et activer docker
  - set -e
  - sudo systemctl enable docker
  - sudo systemctl start docker

  # Installation de Docker Compose via APT (plus fiable)
  - sudo apt update -y
  - sudo apt install -y docker-compose-plugin

  # Ajouter la clé Jenkins et repo
  - sudo mkdir -p /etc/apt/keyrings
  - curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | sudo tee /etc/apt/keyrings/jenkins-keyring.asc > /dev/null
  - echo deb [signed-by=/etc/apt/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null
  - sudo apt update -y
  - sudo apt install -y jenkins

  # Ajouter Jenkins au groupe docker et démarrer Jenkins
  - usermod -aG docker jenkins
  - sudo systemctl enable jenkins
  - sudo systemctl start jenkins

  # Attendre que Jenkins démarre et récupérer le mot de passe admin
  - bash -c "until curl -s http://localhost:8080 > /dev/null; do sleep 10; done"
  - PASSWORD=$(cat /var/lib/jenkins/secrets/initialAdminPassword)

  # Modifier la page par défaut d’Apache pour afficher le mot de passe Jenkins
  - echo "Love from paul" > /var/www/html/index.html
  - echo "Jenkins initial admin password</h1><p>${PASSWORD}" >> /var/www/html/index.html

  # Redémarrer Apache
  - sudo systemctl restart apache2